version: '3'

services:
  # app
  bgs_app:
    container_name: bgs_app
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./docker/src/backend:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  # nginx
  bgs_nginx:
    container_name: bgs_nginx
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./docker/src/backend:/var/www
  # node
  bgs_node:
    container_name: bgs_node
    build: ./docker/node
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./docker/src/frontend:/usr/src/app
  # MariaDB のコンテナ
  bgs_mariadb:
    container_name: bgs_mariadb
    image: mariadb:10.5.4
    environment:
      # ユーザー名やパスワードなどは適宜変更してください
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - ./docker/db/data:/var/lib/mysql
  bgs_phpmyadmin:
    container_name: bgs_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: bgs_mariadb
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
    ports:
        - 8080:80
    volumes:
        - /sessions