version: '3'

services:
  # app
  repono_app:
    container_name: repono_app
    build: ./docker/php
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./docker/src/repono_laravel:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  # nginx
  repono_nginx:
    container_name: repono_nginx
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./docker/src/repono_laravel:/var/www
  # node
  repono_node:
    container_name: repono_node
    build: ./docker/node
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./docker/src/repono_node:/usr/src/app
    command: sh -c "npm install && npm run ${NODE_RUN}"
  # MariaDB のコンテナ
  repono_mariadb:
    container_name: repono_mariadb
    image: mariadb:10.5.4
    environment:
      # ユーザー名やパスワードなどは適宜変更してください
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306
  repono_phpmyadmin:
    container_name: repono_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - repono_mariadb
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: repono_mariadb
    ports:
        - 8080:80